### ISSUE TITLE
Any plans to support integrations?

### ISSUE THREAD

**Issue by jcchavezs** [aws/aws-xray-daemon#1]
At the moment the transport layer is coupled to the AWS server API, is there any plan to support integrations like zipkin for example?

Ping @abhishek
Cc @adriancole

**Comment by abhiksingh** [comment]
@jcchavezs part of the reason for open sourcing the daemon code is to enable the border community to help us with features like the above ask. Do you have a proposal/set of use case in mind? We’d be happy to review and collaborate :)

**Comment by yogiraj07** [comment]
Hi @jcchavezs ,

We have opened issue #4 to discuss design for the multiple integration support. I have written initial thoughts on the design. You are welcome to contribute and discuss various components you are looking for. I am closing this issue and we can track the progress on issue #4.

Thanks,
Yogi
