### ISSUE TITLE
Please add ARM version in ECR Public Gallery

### ISSUE THREAD

**Issue by kitkit201** [aws/aws-xray-daemon#100]
Currently https://gallery.ecr.aws/xray/aws-xray-daemon does not have an ARM version available, but ARM version of xray exists on the Docker repo. 

Please add it to the gallery so we can pull from there.

**Comment by bhautikpip** [comment]
Hi @kitkit201 ,

Thanks for opening this issue. We are currently investigating this issue. I will let you know once I have more updates to share!
