### ISSUE TITLE
Please log trace ID for unprocessed segments

### ISSUE THREAD

**Issue by rhimmelm** [aws/aws-xray-daemon#104]
When the X-Ray daemon fails to upload a trace, it would be great to have the trace ID logged at WARN level or higher. (In batchprocessor.go, line 110 in master, right after "log.Errorf("Unprocessed segment: %v", unprocessedSegment)") As things are now in master, there is either a message without the ID on error or the whole segment on debug. Logging segments is not an option for my customer as segments can get very big. (They got up to 5 Tb per month in one case which created problems along the route.)

The trace ID would be helpful because they will still be able to see other segments of the trace and with those figure out what data they are missing. They have used this way of analysis in the past and don't want to lose it. (Up to version 3.2 the whole segment was always logged on WARN on errors and it contained the trace ID.)

**Comment by wangzlei** [comment]
Thanks for
