### ISSUE TITLE
Different images being published to Docker Hub and ECR Public

### ISSUE THREAD

**Issue by CarlosDomingues** [aws/aws-xray-daemon#128]
The image `aws-xray-daemon:3.2.0` present in Docker Hub has a few pre-installed packages such as sh, curl, etc.... The following command works:

 > docker run -it --entrypoint /bin/sh amazon/aws-xray-daemon:3.2.0

The following does not work:

> docker run -it --entrypoint /bin/sh public.ecr.aws/xray/aws-xray-daemon:3.2.0

I was hopping to switch to ECR public to avoid Docker Hub limits, but unfortunately the image published in ECR public is way too bare bones and needs to be modified for stuff like healthchecks. Also not having /bin/sh makes testing much harder.

Related to #119

**Comment by awssandra** [comment]
Closing this in favor of #119 

Dockherhub will continue to have the amazonlinux base, whereas ECR will continue to use the scratch image to save space. We are continuing to explore a happy medium between the two.
