### ISSUE TITLE
Fargate isnt able to pull the xray deamon 3.x container right now

### ISSUE THREAD

**Issue by icyitscold** [aws/aws-xray-daemon#146]
Not sure if this is region or even account specific but in us-east-2 im seeing builds for all services that reference the 3.x tag fail with the following message:

```
CannotPullContainerError: ref pull has been retried 1 time(s): failed to copy: httpReaderSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/amazon/aws-xray-daemon/manifests/sha256:2d964e1dbe7a8c9f03f4e9580ff00220bc84ce0294539c6...
```

**Comment by awssandra** [comment]
Hey icyitscold,

Seems like a typical issue for ECR - have you checked out these troubleshooting steps? https://aws.amazon.com/premiumsupport/knowledge-center/ecs-pull-container-api-error-ecr/

**Comment by icyitscold** [comment]
Thanks for the response! It's hard to prove that we didn't break anything in the meantime but builds that were working hours ago started failing all of a sudden with no other changes to the infrastructure. New Task definitions started failing with the Pull error and then the automatic rollback to the prior task definition (which was deployed without issue earlier in the day) failed with the same error as the new taskdef.  Just to be sure:

- I confirmed that the IAM role we use to pull container images hasnt been modified.
![image](https://user-images.githubusercontent.com/15347781/121447770-5da5ed80-c964-11eb-909a-aff25bcf45e4.png)
- The task subnet has the appropriate public internet access via the route table
![image](https://user-images.githubusercontent.com/15347781/121447961-c2614800-c964-11eb-973d-814b599ad0c4.png)
- And for the DHCP OptionSet. the  "Domain name servers is set to AmazonProvidedDNS"
![image](https://user-images.githubusercontent.com/15347781/121448167-166c2c80-c965-11eb-9b46-30d6e70623e8.png)


Yes this error message category is common but usually in situations where you're accessing your own private dockerhub and didnt establish the credentials correctly. This is a public dockerhub repo and the error message isn't consistent with an authentication issue - reads more like the image is access is there but fargate cant pull it. ECS doesnt output any logs here so its very hard to tell what's failing. I think it's likely there is an outage on the fargate side or a corrupt container image but hard to say for sure unless other people start noticing the issue.

To add fuel to this mystery fire.. out of my two services that are currently in an indefinite fail/retry loop, 1 of the services just managed to sneak through a successful pull at 20:56 EST, the other had failures as recently as 21:02 EST. Same vpc, same subnet, same role, same ECS cluster, same xray image. My guess is someone is fixing it right now or its a partial outage. But no sign of this on the `https://status.aws.amazon.com/` page

**Comment by icyitscold** [comment]
It's seems like the fargate outage is over now. No changes on my end and all builds stopped failing this morning. Still nothing on the AWS status page for this but closing this issue now
