### ISSUE TITLE
Error: 403 UnrecognizedClientException if the XRay Region is set to Jakarta (ap-southeast-3)

### ISSUE THREAD

**Issue by macirculado** [aws/aws-xray-daemon#185]
I am getting the following error in the xray daemonset pods deployed in ROSA, if the region I specified in the xray config yaml is "ap-southeast-3" (Jakarta).

`2023-01-24T05:52:51Z [Error] Sending segment batch failed with: UnrecognizedClientException:
	status code: 403, request id: 59881ff1-a1c3-4f01-b812-2b1f0541cfe0`

When I tried to specify other region such as ap-southeast-2 (Sydney) and ap-southeast-1 (Singapore), it's working and I can see the data/traces in the AWS X-Ray console.

This is the deployment guide I used, for your reference: [rosa-xray](https://github.com/willgarcia/rosa-xray/)

**Comment by srprash** [comment]
Hi @macirculado 
Can you ensure that the "ap-southeast-3" region is enables in your aws account? It is one of the regions not enabled by default.

**Comment by macirculado** [comment]
Hi @srprash Yes, the "ap-southeast-3" (Jakarta) region is already enabled in our AWS account. We have already deployed other AWS resources in that region.

**Comment by srprash** [comment]
Hi @macirculado Since we are triaging this issue internally, I am closing this one. Please feel free to reopen if you think the issue still pertains to the X-Ray Daemon and could be beneficial to the open-source community. 
Thanks.
