### ISSUE TITLE
App Mesh traces are missing log group for CloudWatch Logs Insights

### ISSUE THREAD

**Issue by mauritz-lovgren** [aws/aws-xray-daemon#204]
## Setup
I am using the x-ray daemon with the App Mesh envoy proxy (using `ENABLE_ENVOY_XRAY_TRACING=1`) in ECS Fargate. Both daemons are deployed as side-car containers with each microservice app main container inside the same ECS task definition and are configured according to official AWS documentation.

Each microservice app outputs the value of the `X-Amzn-Trace-Id` HTTP header (https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-tracingheader) to its application log as a Mapped Diagnostic Context value whenever the header is present, with the hope that the X-Ray traces console UI is then able to correlate them with each trace, but alas.

## Problem
The application logs are **not found** by the X-Ray tracing console UI (no logs show), and when trying to open the CloudWatch logs view for a trace (by pressing the 'View in CloudWatch Logs Insights' button), the resulting search expression lacks log group(s) for the involved services in the trace, which I suspect is the reason why the logs are not correlating?

The start and end date and time selected for the trace is set correctly, so it seems that it is only the log groups that are missing.

### AWS Distro for OpenTelemetry
I see that the OpenTelemetry awsxray exporter can add log group metadata to the trace for this exact purpose (see https://aws-otel.github.io/docs/getting-started/x-ray#configuring-the-aws-x-ray-exporter for details), like this:

```
  exporters:
    awsxray:
      aws_log_groups: [  '/ecs/oneOfOurMicroserviceLogGroups'  ]
```

Is there some similar way to do this with the x-ray daemon (or with the envoy proxy) to ensure that it sets the correct log group for each trace?

## Workaround
- none known for the missing logs in the X-Ray console traces log panel.
- manually adding the relevant log groups in CloudWatch Logs Insights after having pushed the 'View in CloudWatch Logs Insights' button in the X-Ray console. Then the correct logs show up when running the query.

**Comment by atshaw43** [comment]
X-Ray's SDKs and Daemon are not able to send logs to CloudWatch. We only natively support logging to a local file.

There are agents that can move logs from the log file produced by Java (I assume you are using Java) to CloudWatch. I cannot find one developed by AWS, so I cannot recommend them. But you can find them with a Google search.

If this functionality is a deal breaker, my recommendation would be to see if OTel makes sense for you. As you mentioned above, it has this functionality out of the box.

**Comment by mauritz-lovgren** [comment]
> X-Ray's SDKs and Daemon are not able to send logs to CloudWatch. We only natively support logging to a local file.
> 
> 
> 
> There are agents that can move logs from the log file produced by Java (I assume you are using Java) to CloudWatch. I cannot find one developed by AWS, so I cannot recommend them. But you can find them with a Google search.
> 
> 
> 
> If this functionality is a deal breaker, my recommendation would be to see if OTel makes sense for you. As you mentioned above, it has this functionality out of the box.

Yes, I have now converted from the AWS X-Ray daemon to the AWS Distro for Open Telemetry collector, and it works well even though it is still in its early days... The ADOT agent sends traces from the App Mesh Envoy Proxy to X-ray using a slightly different raw format than the X-ray daemon, but the trace Id to log correlation works well, and that is important for us.

**Comment by mauritz-lovgren** [comment]
Closing this as Otel gives us what we need.
