### ISSUE TITLE
Unable to see X-RAY traces

### ISSUE THREAD

**Issue by sandygvs** [aws/aws-xray-daemon#23]
Hi Experts,

I have configured x-ray daemon on aws EC2 as mentioned here [https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-ec2.html](url). I could see the xray service running on the ec2 instance. Below are the x-ray logs,
**$ /usr/bin/xray
2019-02-27T05:57:33Z [Info] Initializing AWS X-Ray daemon 2.1.3
2019-02-27T05:57:33Z [Error] listen udp 127.0.0.1:2000: bind: address already in use

$ cat /var/log/xray/xray.log
2019-01-30T15:21:10Z [Info] Initializing AWS X-Ray daemon 2.1.3
2019-01-30T15:21:10Z [Info] Using buffer memory limit of 160 MB
2019-01-30T15:21:10Z [Info] 2560 segment buffers allocated
2019-01-30T15:21:10Z [Info] Using region: ap-south-1**

**OS INFO:
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"**

But still i don't see any traces in the x-ray console. EC2 instance has xray:* permission. Am i missing any configuration here.

Appreciate your valuable help on this!!!

**Comment by yogiraj07** [comment]
Hi @sandygvs ,
From this message `listen udp 127.0.0.1:2000: bind: address already in use`, a process (possibly old X-Ray daemon) is running on the same port. Can you configure the daemon on another port using [cfg.yaml](https://github.com/aws/aws-xray-daemon/blob/master/daemon/cfg.yaml#L11) or kill the existing process, running on the same port.

Further more, are you sending any data through X-Ray SDK that is instrumented by your app? If yes, which language ?

Traces generated by X-Ray SDK are by default sent to "udp : localhost:2000". And if the X-Ray daemon is listening on the same port, the daemon batches Segments received on the port and sends to X-Ray service. You should make sure, X-Ray SDK is correctly configured with the daemon address if the the address is other than "udp -> localhost:2000"

If the daemon receives any Segment, you would see a log entry : `[Info] Successfully sent batch of 1 segments`. 

From the logs, I would expect to see traces in `ap-south-1` region, if everything is correctly configured.

Please let me know if you need more help.

Thanks,
Yogi

**Comment by sandygvs** [comment]
Thanks for the explanation, it works as expected. There was an issue with instrumenting the app with x-ray, after resolving it. Everything works well!!!

**Comment by jerrychong25** [comment]
Hi @sandygvs ,

For X-Ray, is the following logs means that AWS X-Ray Daemon is running well in my EC2 server?

To test if X-Ray Daemon working fine, how should I do some simple test in my EC2 server?

Logs:
```
2022-06-12T08:46:40Z [Info] Initializing AWS X-Ray daemon 3.3.3
2022-06-12T08:46:40Z [Info] Using buffer memory limit of 19 MB
2022-06-12T08:46:40Z [Info] 304 segment buffers allocated
2022-06-12T08:46:40Z [Info] Using region: ap-southeast-1
2022-06-12T08:46:40Z [Info] HTTP Proxy server using X-Ray Endpoint : https://xray.ap-southeast-1.amazonaws.com
2022-06-12T08:46:40Z [Info] Starting proxy http server on 127.0.0.1:2000
```

Screenshot:
<img width="782" alt="Screenshot 2022-06-12 at 4 56 05 PM" src="https://user-images.githubusercontent.com/15714095/173225472-7c3521de-2946-49db-8af3-eb64696bb519.png">

Thanks in advance!
