### ISSUE TITLE
Support TCP only Segment document transfers

### ISSUE THREAD

**Issue by BHunter2889** [aws/aws-xray-daemon#25]
In the organization my team and I work in, our cloud and security admins have given us the following stipulations for implementing tracing: 

1) We must use standalone EC2 instances, no ECS clusters, etc (Until we completely migrate to Fargate). 
2) We should only have one app running per EC2 instance, no further containers, no daemon sidecar.
3) We can’t bridge between EC2 instances (container to container communication is explicitly disabled)
4) Our organization registry/gateway services must be used for authentication and communication between apps (including the daemon) and they can only support TCP.

Is there any thought to making this a configurable option or something similar? I should add that our organization has a quite large enterprise ecosystem, hence the reason we are trying to begin the process for instrumenting our apps with x-ray.

**Comment by BHunter2889** [comment]
Never mind. The people in charge of budget killed the tracing project. Until we migrate our apps to Fargate anyway, hopefully in the coming months.

**Comment by mbj** [comment]
@BHunter2889 When faced with a similar constraint set I once send the XRay segments directly to the XRay API without an deamon as intermediary. If you trust your app code to batch up the segments this may work well. Downside is that a crashing app takes the (partial) batch away before sending it out.

**Comment by awssandra** [comment]
There are drawbacks to front-loading the SDKs to handle sending the segments. The optimizations for the daemon and SDK were built on UDP for speed and efficiency at a cost of reliability. Some of our SDKs do not have the necessary APIs to change their streaming logic, a gap which we are attempting to close.

Please feel free to reach-out at a later date when you know your integration timeline, we'd be happy to help finding a solution viable to for your constraints.
