### ISSUE TITLE
Must be run with elevated privileges

### ISSUE THREAD

**Issue by mnowotnik** [aws/aws-xray-daemon#28]
On Linux aws-xray-daemon tries implicitly to gain access to file: `/etc/amazon/xray/cfg.yaml` , even with `-c` option. However, this file is not in a user tree hence it requires sudo access.  Related log entry:
`Error] Error occur when using config flag: open /etc/amazon/xray/cfg.yaml: permission denied`

**Comment by shengxil** [comment]
Thanks for submitting the PR. We have verified the fix.

**Comment by shengxil** [comment]
The fix is GA now

**Comment by mnowotnik** [comment]
This doesn't really fix the issue. The access to `/etc/amazon/xray/cfg.yaml` should not be necessary with the `-c` flag.

**Comment by shengxil** [comment]
> This doesn't really fix the issue. The access to `/etc/amazon/xray/cfg.yaml` should not be necessary with the `-c` flag.

Hi, could you elaborate more on the issues? Per our test on Linux the `-c` flag is not required with the latest fix
