### ISSUE TITLE
failed to load config file - unsupported expression

### ISSUE THREAD

**Issue by stimpy77** [aws/aws-xray-daemon#37]
I am new to AWS and x-ray. I set up for myself a running instance of some cloud services, the app is working and x-ray logs. However, I'm trying to run the app locally on my workstation while capturing diagnostics to x-ray, and despite having successfully set up AWS profiles on my workstation and getting the key and secret for the root of the account I'm building for, I am getting the following error when I run this command on my local machine (for local workstation execution of an AWS app):

````
set AWS_PROFILE=myprofile
xray_windows.exe -o -n us-east-2
````

````
2019-12-11T14:04:14-07:00 [Info] Initializing AWS X-Ray daemon 3.2.0
2019-12-11T14:04:14-07:00 [Info] Using buffer memory limit of 161 MB
2019-12-11T14:04:14-07:00 [Info] 2576 segment buffers allocated
2019-12-11T14:04:14-07:00 [Error] Error in creating session object : SharedConfigLoadError: failed to load config file, C:\Users\Jon\.aws\credentials
caused by: INIParseError: unsupported expression {expr {1 STRING 0 [65533 65533]} true []}
.
````

The entire contents of the file located at C:\Users\Jon\\.aws\credentials is (actual keys omitted here):
````
[myprofile]
aws_access_key_id = 01234
aws_secret_access_key = 1234
````
I also tried using `[default]` at the top of the file along with running `set AWS_PROFILE=default`, same error.

I presume the daemon is fine; so what am I doing wrong?

**Comment by stimpy77** [comment]
OK, this is a misfire. I'm able to repro the error with ...

````
aws ec2 describe-instances --profile myprofile
````

It doesn't relate to the x-ray daemon.

**Comment by stimpy77** [comment]
I resolved this by deleting the file running (with AWS CLI tools for Windows installed)

````
aws configure --profile myprofile
````

The file looks the same, so I dunno. Maybe a different encoding format? *shrug*

Jon

**Comment by kainwei** [comment]
I have met this as well, I am using powershell as a cicd agent. I need to use s3 backend as a terraform state store. So I just echo aws access id and secret in to ~/.aws/credentials, but this error happened. Then I found the root cause is windows file format, we need to transfer the file to linux file format. I lookup how to transfer windows file to linux file in powershell, so the finall solution is :
    `[string]::Join( "`n", (gc  ~/.aws/cred)) | sc  ~/.aws/credentials`
below is my whole codes:
    ```
if (Test-Path ~/.aws) {
  Remove-Item ~/.aws -Recurse -Force -EA SilentlyContinue
}
mkdir ~/.aws
echo "[services]" > ~/.aws/cred
echo "aws_access_key_id = ${bamboo.S3_BACK_ACCESS}" >> ~/.aws/cred
echo "aws_secret_access_key = ${bamboo.S3_BACK_SECRET}" >> ~/.aws/cred
[string]::Join( "`n", (gc  ~/.aws/cred)) | sc  ~/.aws/credentials
cat ~/.aws/credentials
```

Hope it can help others!
