### ISSUE TITLE
Adding support for ECS_ENABLE_CONTAINER_METADATA and ECS_CONTAINER_METADATA_FILE

### ISSUE THREAD

**Issue by mauro76** [aws/aws-xray-daemon#40]
Hello,

I have been contacting AWS Support on my company's AWS account about this, but I'm using my personal Github profile for the request.
We are using the aws-xray-daemon as a side container on ECS, and we use bridged networking. The ECS instances under the hood are using the `iptables` rule suggested on https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html, which prevents the daemon from accessing the region through the metadata.
We could provide the AWS_REGION as environment variable to all the task definitions, but I feel like a solution across the board would be best.

I've looked into using ECS_ENABLE_CONTAINER_METADATA and ECS_CONTAINER_METADATA_FILE from https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-metadata.html and AWS Support agrees it would be the best option.
I'd be happy to work on a pull request, if you agree it's something you are willing to accept.

Regards,
Mauro

**Comment by bf-sodle** [comment]
This affects more than just fetching the region - you can't fetch credentials from the ECS Task Metadata Endpoint either. As far as I can tell, it's impossible to run the X-Ray Daemon on ECS if the EC2 Instance Metadata Service isn't exposed to the container.

The EC2 metadata service is unavailable by default on the latest ECS Optimized AMIs, as well as on Fargate, and it's considered a best practice to block it in other implementations.

Is this a limitation of the X-Ray daemon specifically, or of the underlying AWS SDK for Go?

**Comment by mauro76** [comment]
I could run the X-Ray daemon manually on an ECS test cluster with EC2 metadata turned off, by providing the AWS_REGION as a variable. I'd rather prefer it as a ECS metadata, which https://github.com/aws/aws-xray-daemon/pull/41 would support.

Indeed blocking EC2 metadata is the right thing to do. We have it on our ECS cluster running an older ECS Optimised AMI.
The EC2 metadata service if blocked by an iptables rule, and it should affect any container not specifically X-Ray. 
It's a bad practice to use credentials, the IAM role assigned to the task should be all you need.

**Comment by bf-sodle** [comment]
When I run the agent on ECS and manually provide AWS_REGION, it still crashes because it then attempts to retrieve credentials from the EC2 metadata service.

I'm not suggesting that you should use anything other than the task role, but under the hood, there are still credentials. In order to assume the task role, the SDK or CLI needs to grab the task role's access key, secret, and session token from ECS metadata. For some reason the X-Ray agent isn't attempting to do this, so it fails.

**Comment by willarmiros** [comment]
Hi @mauro76, 
Thank you for raising this issue. We are currently looking into #41 and once we are able to prioritize testing it we should be able to merge it.

**Comment by srprash** [comment]
Hi @mauro76 
This support has been released in v3.3.0 but we recommend using v3.3.1 which includes bug fixes as well. Please see the [changelog](https://github.com/aws/aws-xray-daemon/blob/master/CHANGELOG.md) for details.
