### ISSUE TITLE
Daemon starts before network is available

### ISSUE THREAD

**Issue by rosswilson** [aws/aws-xray-daemon#5]
We're deploying the daemon onto CentOS instances are are seeing a recurring issue where the daemon attempts to start before networking is available.

The daemon fails because it cannot access the metadata service to obtain the current region:

```
2018-04-16T14:56:05Z [Info] Initializing AWS X-Ray daemon 2.1.0
2018-04-16T14:56:05Z [Info] Using buffer memory limit of 19 MB
2018-04-16T14:56:05Z [Info] 304 segment buffers allocated
2018-04-16T14:56:05Z [Error] Unable to retrieve the region from the EC2 instance RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/placement/availability-zone: dial tcp 169.254.169.254:80: connect: network is unreachable
2018-04-16T14:56:05Z [Error] Cannot fetch region variable from config file, environment variables and ec2 metadata.
```

A `service xray start` on an instance works as expected.

Are you aware of this and do you have any suggestions?

**Comment by rosswilson** [comment]
I think the service file should have `After=network-online.target` within the `[Unit]` block. This should make the daemon wait for networking to be available before attempting to start.

I'll fire a PR across for review.

**Comment by niklasR** [comment]
I've noticed the same thing here.
I _think_ I've added the `After=network-online.target` correctly, and it still doesn't always work, showing the same error in the log.

**Comment by haotianw465** [comment]
The PR is merged and we will release a new version with all latest changes as soon as possible. Thank you for your patience.

**Comment by yogiraj07** [comment]
H @rosswilson ,

We have made daemon release V2.1.2: https://github.com/aws/aws-xray-daemon/releases/tag/V2.1.2 which includes this PR.

Please let us know if you have any questions.

Thanks,
Yogi

**Comment by rockse** [comment]
This is still happening for us in AWS X-Ray daemon 3.2.0 
```
[Error] Cannot fetch region variable from config file, environment variables and ec2 metadata.
caused by: Get http://169.254.169.254/latest/dynamic/instance-identity/document: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
