### ISSUE TITLE
Support config for send batch throttling?

### ISSUE THREAD

**Issue by lsanders** [aws/aws-xray-daemon#55]
I'm getting:
```
Sending segment batch failed with: ThrottlingException: Rate exceeded
```

I'm running the daemon inside a container running as a AWS Batch task. Many of my requests send just fine. The source of the segments are coming from `aws-xray-sdk`. But this error is originating from the daemon.

I do have concurrent batch jobs using the same role, but I think this limit is a AWS account limit?

Is there away to tune the max retries or enable throttling on the daemon?

**Comment by willarmiros** [comment]
Hi @lsanders, 

> I think this limit is a AWS account limit?

Your suspicion is correct that the throttling limit is on a per-AWS account basis. Sending too many segments at once in the same account & region can trigger throttling and result in segments getting dropped. I'd recommend reaching out to AWS Customer support to discuss giving your account a higher throttling threshold.

> Is there away to tune the max retries or enable throttling on the daemon?

There is not a way to configure such properties on the daemon, all configurable properties can be found [here](https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-configuration.html).

Please let me know if you have any other questions or I'll close this out.

**Comment by lsanders** [comment]
Thanks for your response!

I see `Concurrency` as a configurable settings. Would tuning that help me overcome rate limiting?

**Comment by willarmiros** [comment]
It's possible, you can try to reduce the concurrency setting to see if more segments make it through. That might cause issues with segments overflowing in the daemon's buffer because there are clearly a lot of them and they'll be sending more slowly now. So you might have to increase the `TotalBufferSizeMB` as well.
