### ISSUE TITLE
X-Ray Sampling Rules :: Error reading response

### ISSUE THREAD

**Issue by gncj** [aws/aws-xray-daemon#56]
### Issue
we are getting an error when X-Ray executes the Sampling Rules.

### Current Behavior
this happens every minute when our app is running. The problem occurs when processing the 'createdAt' of class SamplingRuleRecord present in GetSamplingRulesResult.
We think this may have started to happen when we started using version 2.6.0 of X-Ray SDK.

### Application Error
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 2020-06-20T16:31:09Z [Info] Successfully sent batch of 1 segments (0.015 seconds)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 20-Jun-2020 16:31:15.531 INFO [pool-5-thread-1] com.amazonaws.xray.strategy.sampling.pollers.RulePoller.pollRule Polling sampling rules.
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 20-Jun-2020 16:31:15.558 SEVERE [pool-5-thread-1] com.amazonaws.xray.strategy.sampling.pollers.RulePoller.lambda$start$0 Encountered error polling GetSamplingRules:
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 	com.amazonaws.xray.internal.XrayClientException: Error reading response.
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.amazonaws.xray.internal.UnsignedXrayClient.sendRequest(UnsignedXrayClient.java:136)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.amazonaws.xray.internal.UnsignedXrayClient.getSamplingRules(UnsignedXrayClient.java:88)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.amazonaws.xray.strategy.sampling.pollers.RulePoller.pollRule(RulePoller.java:100)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.amazonaws.xray.strategy.sampling.pollers.RulePoller.lambda$start$0(RulePoller.java:72)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at java.base/java.lang.Thread.run(Thread.java:834)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 	Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.Date` out of VALUE_NUMBER_FLOAT token
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5  at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 38] (through reference chain: com.amazonaws.services.xray.model.GetSamplingRulesResult["SamplingRuleRecords"]->java.util.ArrayList[0]->com.amazonaws.services.xray.model.SamplingRuleRecord["CreatedAt"])
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1464)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1238)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1148)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseDate(StdDeserializer.java:511)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateBasedDeserializer._parseDate(DateDeserializers.java:200)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:290)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:273)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3471)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		at com.amazonaws.xray.internal.UnsignedXrayClient.sendRequest(UnsignedXrayClient.java:134)
/ecs/IndexerTask ecs/IndexerContainer/186e60110e7749b3b35d8ac761d56ea5 		... 9 more
/ecs/IndexerTask ecs/IndexerContainer/186

### Environment
AWS Java SDK version used: 2.13.40
AWS X-Ray SDK version used: 2.6.0
Jackson version used: 2.11.0
JDK version used: jdk11-corretto
Operating System and version: docker tomcat:9-jdk11-corretto
Webapp build and deploy to ECS Fargate Cluster with AWS Code Pipeline

**Comment by anuraaga** [comment]
Thanks for reporting! We've identified the issue is in the SDK and will proceed on https://github.com/aws/aws-xray-sdk-java/issues/170
