### ISSUE TITLE
Reduce debug logging

### ISSUE THREAD

**Issue by anuraaga** [aws/aws-xray-daemon#62]
There are some suspicious debug logging statements that seem spammy enough that debug logging can't practically be enabled for debugging real issues. For example, when reading from read buffer

https://github.com/aws/aws-xray-daemon/blob/master/pkg/ringbuffer/ringbuffer.go#L83

We should reduce these to trace log level so debug logging can be enabled for debugging normal issues, not code issues, such as unprocessed segments.

**Comment by srprash** [comment]
Resolved in v3.3.1
