### ISSUE TITLE
Arm64 / Graviton2 support via multi-arch images

### ISSUE THREAD

**Issue by scottmalkie** [aws/aws-xray-daemon#68]
Hello!

Would it be possible to build Arm64 images and make https://hub.docker.com/r/amazon/aws-xray-daemon/tags multi-arch so it can be used on Graviton/Graviton2-based container hosts?

Thanks!

**Comment by willarmiros** [comment]
Hi @scottmalkie,

Thanks for the request! We'll see if we can add that additional architecture to our DockerHub release. As a workaround for now, you can clone this repo and build an arm64 binary: https://github.com/aws/aws-xray-daemon#build-with-arm

**Comment by scottmalkie** [comment]
Looks like this was done for the [3.2.0 release](https://hub.docker.com/r/amazon/aws-xray-daemon/tags) !  Thanks so much.
