### ISSUE TITLE
AWS XRay Daemon High CPU Usage

### ISSUE THREAD

**Issue by ncjones** [aws/aws-xray-daemon#70]
Last week we deployed the XRay Daemon as a daemon set to our EKS cluster and we have seen a marked increase in CPU usage. Our cluster nodes, which typically idle at 6-8% CPU, have been running at around 17-20%. Scaling the daemonset back to zero restored the node CPU back to around 6%. The image we are using is amazon/aws-xray-daemon:3.x (https://hub.docker.com/layers/amazon/aws-xray-daemon/3.x/images/sha256-0c5b0deb0332e28669059fa936662cb05cbe47864bdd91e9d26cb479df62cc1d?context=explore). I didn't see any errors in the XRay Daemon logs.

**Comment by wangzlei** [comment]
Hello,

The CPU usage of X-Ray Daemon is in line with the throughput, if no new X-Ray data input, the CPU usage of X-Ray Daemon should be 0. So, firstly we can identify the problem from if your throughput is getting high as scaling the daemonset.
Could you login to the X-Ray Daemon container and use top command to check the `xray` process CPU usage? If it is high, please enable debug level log by adding `-l debug` in X-Ray Daemon command, then check if there are outstanding logs.
Another

**Comment by ncjones** [comment]
@wangzlei I rechecked our Kubernetes node CPU utilization today and could not see any correlation with the XRay daemon. Seems like we have something else going on. I will close this for now.
