### ISSUE TITLE
Feature: Publish to ECR Public Gallery

### ISSUE THREAD

**Issue by aoggz** [aws/aws-xray-daemon#83]
The [ECR public gallery](https://gallery.ecr.aws/) was [announced at re:Invent yesterday](https://aws.amazon.com/about-aws/whats-new/2020/12/announcing-amazon-ecr-public-and-amazon-ecr-public-gallery/). It would be very helpful to have this image published there, in addition to Dockerhub.

**Comment by willarmiros** [comment]
Hi @aoggz thanks for the request! We plan on publishing to ECR public gallery, and have updated #79 and #81 to reflect such.

**Comment by aoggz** [comment]
Oh, that's great news! Thank you @willarmiros for all your work on this project!

**Comment by mmmeff** [comment]
Any update on this?

**Comment by mmmeff** [comment]
I noticed the alpha image just popped in at https://gallery.ecr.aws/xray/aws-xray-daemon

Nice! Looking forward to seeing the `:lastest` tag arrive.

**Comment by bhautikpip** [comment]
Hi All,

We have merged alpha tag publisher workflow (https://github.com/aws/aws-xray-daemon/pull/87) so that will publish alpha tag on every merge to public ECR daemon repository. For production tags we still are waiting on Daemon 3.3.0 release. Stay tuned for more updates :)

NOTE: We do not recommend to use alpha tags in production environment.

**Comment by richardgavel** [comment]
Can you guys publish the prior production versions of the Docker image to that public repo as well? We are being blocked at this point by the Docker hub throtttling limits.

**Comment by bhautikpip** [comment]
X-Ray Daemon image tag `3.2.0` is now available to public ECR - https://gallery.ecr.aws/xray/aws-xray-daemon

https://integ-docs-aws.amazon.com/xray/latest/devguide/xray-daemon.html

**Comment by pingleig** [comment]
@bhautikpip I think this issue can be closed?
