### ISSUE TITLE
When I run the program, the following error appears

### ISSUE THREAD

**Issue by wangfan0524** [aws/aws-xray-daemon#93]
{"level":"info","msg":"Couldn't describe resources for region us-east-2: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\n","time":"2021-01-23T17:25:48Z"}

**Comment by awssandra** [comment]
Hi wangfan0524,

It appears you do not have AWS credentials setup on your machine. Please see: https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon.html#xray-daemon-permissions
