### ISSUE TITLE
Does aws-xray-daemon support SamplingRules?

### ISSUE THREAD

**Issue by arthuroz** [aws/aws-xray-daemon#96]
Hi there,

We are using xray-daemon with App Mesh in ECS (Fargate) as instructed in https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-ecs.html#xray-daemon-ecs-build.

Healthcheck counts for most of the x-ray traces in our dev environment so we'd like to use Sampling Rules to exclude them, but xray-daemon is NOT loading sampling rules from X-ray console, attached screenshot is ECS logs for xray-daemon.

![image](https://user-images.githubusercontent.com/978866/107601270-569ef500-6c7a-11eb-879b-e958425e8011.png)

I thought about baking a config file into a Docker image and then configure the xray-daemon to use it. But after having a look at the code, xray-daemon does NOT seem to [configure sampling rules](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-go-configuration.html) at all.

Does this mean we **must** use xray-sdk to instrument our applications if we'd like to exclude health check paths from xray tracing?

Thank you!

Best regards,
Arthur

**Comment by awssandra** [comment]
Hi arthuroz,

Sampling is always done at the 'inflection point', or when a request enters a tracing-enabled system and the trace starts, either automatically through the AWS service with X-Ray enabled or through the X-Ray SDK with the X-Ray Daemon.

I assume the health check for the ECS application does not route through AWS App Mesh. If this is the case, you should be able to control the sampling and sampling rules. But, the Daemon only *relays* these sampling rules, the request for the sampling rules is done via the X-Ray SDK of your choosing. The X-Ray SDK is responsible for handling sampling, as this also generates traces.

If the inflection point is AWS App Mesh, then App Mesh itself is responsible for making the sampling decisions in this case. AWS App Mesh, much like AWS Lambda, does not support custom sampling rules today.

Can you post a raw trace (JSON data from the "raw trace" tab) of the trace so we can see where the inflection point is?

Thanks,
Sandra

**Comment by arthuroz** [comment]
Hi @awssandra,

Thank you for prompt response, here is the raw trace. Healthcheck seems to route through AWS App Mesh, please correct me if I am wrong.

It would be great if daemon could pull sampling rules from X-Ray console and configure it accordingly (something like [requested here](https://github.com/aws/aws-app-mesh-roadmap/issues/95)), because requests such as health check is not initiated by applications.

{
    "Id": "1-6025aa00-95c99d17fac840309e0fd90f",
    "Duration": 0.001,
    "LimitExceeded": false,
    "Segments": [
        {
            "Id": "3c16b94bbf1db5ac",
            "Document": {
                "id": "3c16b94bbf1db5ac",
                "name": "adr-svc-mesh-local/mdc",
                "start_time": 1613081088.1902287,
                "trace_id": "1-6025aa00-95c99d17fac840309e0fd90f",
                "end_time": 1613081088.1908295,
                "http": {
                    "request": {
                        "url": "https://mdc.svc.mesh.local:8080/healthcheck",
                        "method": "GET",
                        "user_agent": "Envoy/HC",
                        "client_ip": "10.0.3.224",
                        "x_forwarded_for": false
                    },
                    "response": {
                        "status": 200,
                        "content_length": 15
                    }
                },
                "aws": {
                    "app_mesh": {
                        "mesh_name": "adr-svc-mesh-local",
                        "virtual_node_name": "mdc"
                    }
                },
                "annotations": {
                    "response_flags": "-",
                    "component": "proxy",
                    "upstream_cluster": "cds_ingress_adr-svc-mesh-local_mdc_http_8080",
                    "request_size": "0",
                    "downstream_cluster": "-",
                    "node_id": "arn:aws:appmesh:ap-southeast-2:696723395816:mesh/adr-svc-mesh-local/virtualNode/mdc"
                },
                "origin": "AWS::AppMesh::Proxy"
            }
        }
    ]
}

**Comment by awssandra** [comment]
Yep, looks like that is App Mesh doing the sampling.

I would suggest opening up a discussion on their forums: https://forums.aws.amazon.com/forum.jspa?forumID=325&start=0
